name: Plano Diário

on:
  schedule:
    - cron: "0 9 * * *"   # executa 9h UTC (~06h no horário de Brasília)
  workflow_dispatch:      # permite rodar manualmente também

jobs:
  run-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CHAT_API_KEY: ${{ secrets.CHAT_API_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          PUSH_BULLET_API_KEY: ${{ secrets.PUSH_BULLET_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python notion_tasks.py
